services:
  - type: web
    name: lmk-official
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    rootDir: frontend
    routes:
      # Rewrites all requests to index.html for React Router support
      - type: rewrite
        source: /*
        destination: /index.html
